CDH-66422: Running MRIT/HMRIT without -D 'mapreduce.job.user.classpath.first=true' in combination with Solr 7 causes the following Solr exception in the reducers because Hadoop puts the metrics-core-3.0.1 jar onto the classpath before the metrics-core-3.2.x jar that's required by Solr 7:
2018-01-31 13:00:39,756 INFO [main] org.apache.solr.hadoop.SolrRecordWriter: Constructed instance information solr.home /yarn/nm/usercache/systest/appcache/application_1517357945005_0017/container_1517357945005_0017_01_000012/tmp/1517432439629-0 (/yarn/nm/usercache/systest/appcache/application_1517357945005_0017/container_1517357945005_0017_01_000012/tmp/1517432439629-0), instance dir /yarn/nm/usercache/systest/appcache/application_1517357945005_0017/container_1517357945005_0017_01_000012/tmp/1517432439629-0, conf dir /yarn/nm/usercache/systest/appcache/application_1517357945005_0017/container_1517357945005_0017_01_000012/tmp/1517432439629-0/conf, writing index to solr.data.dir hdfs://whoschek-systest63-1.gce.cloudera.com:8020/tmp/search-694ff7ab-8634-400d-9142-6bb8445ee553/reducers/_temporary/1/_temporary/attempt_1517357945005_0017_r_000000_0/part-r-00000/data, with permdir hdfs://whoschek-systest63-1.gce.cloudera.com:8020/tmp/search-694ff7ab-8634-400d-9142-6bb8445ee553/reducers/_temporary/1/_temporary/attempt_1517357945005_0017_r_000000_0/part-r-00000
2018-01-31 13:00:39,808 INFO [main] org.apache.solr.core.SolrXmlConfig: Loading container configuration from /yarn/nm/usercache/systest/appcache/application_1517357945005_0017/container_1517357945005_0017_01_000012/tmp/1517432439629-0/solr.xml
2018-01-31 13:00:41,041 INFO [main] org.apache.solr.core.SolrXmlConfig: MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@3972a855, but no JMX reporters were configured - adding default JMX reporter.
2018-01-31 13:00:42,577 ERROR [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoSuchMethodError: com.codahale.metrics.MetricRegistry.meter(Ljava/lang/String;Lcom/codahale/metrics/MetricRegistry$MetricSupplier;)Lcom/codahale/metrics/Meter;
	at org.apache.solr.metrics.SolrMetricManager.meter(SolrMetricManager.java:577)
	at org.apache.solr.handler.RequestHandlerBase.initializeMetrics(RequestHandlerBase.java:144)
	at org.apache.solr.core.CoreContainer.createHandler(CoreContainer.java:1491)
	at org.apache.solr.core.CoreContainer.load(CoreContainer.java:524)
	at org.apache.solr.hadoop.SolrRecordWriter.createEmbeddedSolrServer(SolrRecordWriter.java:183)
	at org.apache.solr.hadoop.SolrRecordWriter.<init>(SolrRecordWriter.java:127)
	at org.apache.solr.hadoop.SolrOutputFormat.getRecordWriter(SolrOutputFormat.java:162)
	at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.<init>(ReduceTask.java:542)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:615)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:390)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1962)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168)

This change automatically sets mapreduce.job.user.classpath.first=true without requiring the user to specify it via a CLI option. This way we retain compatibility with the CDH5 version of hbase-indexer (which doesn't require mapreduce.job.user.classpath.first=true because it runs in combination with Solr 4).

Change-Id: I5a4c0decfda8687684176ad541e111746e5c7f7b