CLOUDERA-BUILD: Fix test framework error (solr server requires different servlet api version than hadoop): java.lang.NoSuchMethodError: javax.servlet.ServletInputStream.isFinished()Z 	at org.apache.solr.servlet.SolrDispatchFilter.consumeInputFully(SolrDispatchFilter.java:284)